# -*- coding: utf-8 -*-
"""imdb rating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wopFzyxQHr260ehkfeZ29xXvfgXdXMd
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('IMDb Movies India.csv',encoding='ISO-8859-1')
data.head(10)

data.tail(10)

data.shape

print("number of rows",data.shape[0])
print("number of columns",data.shape[1])

"""get info about dataset"""

data.info()

"""check the missing values"""

print("Any missing value?",data.isnull().values.any())

data.isnull().sum()

sns.heatmap(data.isnull())

per_missing=data.isnull().sum()*100/len(data)
per_missing

"""Drop all the missing values"""

data.dropna(axis=0)

"""Check duplicate data"""

dup_data=data.duplicated().any()

print("are there any duplicate vales",dup_data)

data=data.drop_duplicates()
data

"""Overall statistivs about the dataframe"""

data.describe(include='all')

"""movie runtime>=180 min

"""

data.columns

data['Duration']

data.columns

sns.barplot(x='Year',y='Votes',data=data)

data.columns

data.groupby('Year')['Rating'].mean().sort_values()

sns.barplot(x='Year',y='Rating',data=data)
plt.title("Revenue by Year")
plt.show()

data.columns

data.groupby('Director')['Rating'].mean().sort_values(ascending=False)

data.columns

data.nlargest(10,'Duration')[['Name','Duration']]

sns.barplot(x='Duration',y='Name',data=data)

data['Year'].value_counts()

sns.countplot(x='Year',data=data)

sns.barplot(x='Rating',y='Name',data=data)

data.columns

"""data.columns"""

data.groupby('Year')['Rating'].mean().sort_values(ascending=False)

def rating(rating):
  if rating>=7.0:
    return "Excellent"
  elif rating>=6.0:
    return "Good"
  else:
    return "Average"

data['rating_cat']=data['Rating'].apply(rating)

data.head()

data['Genre'].dtype

data['Genre'].str.contains('Action')

# Check for missing values in the 'Genre' column
missing_values = data['Genre'].isna()

# Filter out missing values and then count the occurrences of 'Action' genre
action_count = len(data[~missing_values]['Genre'].str.contains('Action'))

action_count

data['Genre']

list1=[]
for value in data['Genre']:
  list1.append(value.split(','))

list1 = []
for value in data['Genre']:
    if isinstance(value, str):
        list1.append(value.split(','))
    else:
        list1.append([])
list1

one_d=[]
for item in list1:
  for item1 in item:
    one_d.append(item1)

one_d

uni_list=[]
for item in one_d:
  if item not in uni_list:
    uni_list.append(item)

len(uni_list)

from collections import Counter

Counter(one_d)